language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - 5.5
    - 5.6
    - nightly
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

install:
    - composer install
    - composer self-update

script:
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
    - php console psysh -V
