language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly

matrix:
    fast_finish: true

install:
    - composer install --prefer-dist

script:
    - bin/phpunit
    - php bin/console psysh -V

notifications:
    email: false
